version: '2'
services:
 syslog-app:
  image: ivixq/alpine-s6-edge-rsyslog-loganalyer
#  image: alpine-s6-edge-syslog
  container_name: syslog-app
  ports:
   - 514:514/udp
   - 10514:10514/tcp
   - 10051:10051/tcp
   - 10052:10052/tcp
   - 80:80/tcp
#  volumes:
#   - /data/syslog.cfg:/cfg
  environment:
   - DEBUG_MODE=true
   - HTTP_FQDN=192.168.1.199
   - DB_HOST=syslog-db
   - DB_USER=syslog
   - DB_NAME=Syslog
   - DB_PASS=syspass
  restart: always
  networks:
   - app-net

 syslog-db: 
#  image: alpine-s6-edge-mariadb
  image: ivixq/alpine-s6-edge-mariadb
  container_name: syslog-db
  volumes:
   - /data/mysql/syslog:/var/lib/mysql
   - /data/mysql.cfg:/etc/conf.d
  environment:
   - DEBUG_MODE=true
   - MYSQL_ROOT_PASSWORD=123456
   - MYSQL_USER=syslog
   - MYSQL_DATABASE=Syslog
   - MYSQL_PASSWORD=syspass
  restart: always
  networks:
   - app-net

networks:
 app-net:
  external: true
