#!/usr/bin/with-contenv bash
## Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
  set -x
fi

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

## Start Rsyslog Server
echo "[i] Starting Rsyslog Server"
exec /usr/sbin/rsyslogd -n
