#!/usr/bin/with-contenv bash
## Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
    set -x
fi

## default parameters
DB_HOST=${DB_HOST:-"syslogdb"}
DB_PORT=${DB_PORT:-"3306"}
DB_NAME=${DB_NAME:-"Syslog"}
DB_USER=${DB_USER:-"syslog"}
DB_PASS=${DB_PASS:-"syspass"}
SYSLOG_ADMIN=${SYSLOG_ADMIN:-"admin"}
ADMIN_PASS=${ADMIN_PASS:-"admin"}

INIT_FILE="`basename $0`-init"
mysqlcmd="mysql -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASS -A -N"

if [ ! -f /tmp/state/$INIT_FILE ]; then
    while ! $mysqlcmd -e "USE $DB_NAME" >/dev/null 2>&1; do
        sleep 1
    done
  
    $mysqlcmd -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
    if ! $mysqlcmd $DB_NAME -e "select count(*) from users;"; then
        echo "[i] import inital data"
        $mysqlcmd -D "$DB_NAME" < "/etc/cfg/mysql-createDB.sql"
    fi

    sed -e "s/<DB_HOST>/$DB_HOST/g" \
        -e "s/<DB_NAME>/$DB_NAME/g" \
        -e "s/<DB_USER>/$DB_USER/g" \
        -e "s/<DB_PASS>/$DB_PASS/g" -i /etc/rsyslog.conf
    
    sed -e "s/<DB_HOST>/$DB_HOST/g" \
        -e "s/<DB_NAME>/$DB_NAME/g" \
        -e "s/<DB_USER>/$DB_USER/g" \
        -e "s/<DB_USER>/$DB_PASS/g" \
        -e "s/<SYSLOG_ADMIN/$SYSLOG_ADMIN/g" \
        -e "s/<ADMIN_PASS>/$ADMIN_PASS/g" -i /var/www/html/loganalyzer/install.php

    
    mkdir -p /tmp/state
    touch /tmp/state/$INIT_FILE
fi

