#!/usr/bin/with-contenv bash

if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
  set -x
fi

HTTP_FQDN=${HTTP_FQDN:-""}

INIT_FILE="`basename $0`-init"

if [ ! -f /tmp/state/`basename $0`-init ]; then  
  sed -i -e "s/Group apache/Group www-data/g" /etc/apache2/httpd.conf
  sed -i -e "s/<HTTP_FQDN>/$HTTP_FQDN/g" /etc/apache2/conf.d/loganalyer.conf
  touch /tmp/state/`basename $0`-init
fi

mkdir -p /run/apache2
chown -R apache /run/apache2
